# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aniket Bhatia
full_name: Aniket Bhatia
email: aniketb@iitb.ac.in
email2: aniketbhatia2107@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aniketb21.github.io" # the base hostname & protocol for your site
github_username:  aniketb21
twitter_username: aniketb21
linkedin_username: aniketb21
stackoverflow: aniketb21
include: ['_pages']
footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag

theme: jekyll-theme-cayman